//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FastCoinTrader.EnitityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_FAQ
    {
        public System.Guid pk_tbl_FAQ { get; set; }
        public string tbl_FAQ_Title { get; set; }
        public string tbl_FAQ_Content { get; set; }
        public System.DateTime tbl_FAQ_DateCreated { get; set; }
    }
}
