//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FastCoinTrader.EnitityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Wallet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Wallet()
        {
            this.tbl_Sales = new HashSet<tbl_Sales>();
            this.tbl_Buys = new HashSet<tbl_Buys>();
        }
    
        public System.Guid pk_tbl_Wallet { get; set; }
        public System.Guid fk_tbl_UserAccount { get; set; }
        public decimal tbl_Wallet_ZARBalance { get; set; }
        public decimal tbl_Wallet_BTCBalance { get; set; }
        public string tbl_Wallet_BTCAddress { get; set; }
        public string tbl_Wallet_BankAccNumber { get; set; }
        public string tbl_Wallet_BankName { get; set; }
        public string tbl_Wallet_BankBranchName { get; set; }
        public string tbl_Wallet_BankBranchNumber { get; set; }
        public System.DateTime tbl_Wallet_DateCreated { get; set; }
        public System.DateTime tbl_Wallet_DateLastModified { get; set; }
        public decimal tbl_Wallet_ZARPending { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Sales> tbl_Sales { get; set; }
        public virtual tbl_UserAccount tbl_UserAccount { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Buys> tbl_Buys { get; set; }
    }
}
