//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FastCoinTrader.EnitityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Sales
    {
        public System.Guid pk_tbl_Sales { get; set; }
        public System.Guid fk_tbl_Wallet { get; set; }
        public decimal tbl_Sales_BTCTargetAmount { get; set; }
        public decimal tbl_Sales_ZARPrice { get; set; }
        public decimal tbl_Sales_ZARTotal { get; set; }
        public decimal tbl_Sales_BTCSold { get; set; }
        public string tbl_Sales_Status { get; set; }
        public System.DateTime tbl_Sales_DateCreated { get; set; }
        public System.DateTime tbl_Sales_DateLastModified { get; set; }
    
        public virtual tbl_Wallet tbl_Wallet { get; set; }
    }
}
